"""KB Generator Part 2 — diseases 16-31."""
import json
from pathlib import Path

DISEASES_PART2 = [
{"id":"gerd","disease_name":"GERD","icd10_code":"K21","description":"Gastroesophageal reflux disease — chronic acid reflux where stomach acid flows back into the esophagus.","common_symptoms":["heartburn","acid regurgitation","difficulty swallowing","chest pain after eating"],"rare_symptoms":["chronic cough","laryngitis","new or worsening asthma","disrupted sleep"],"causes":["Weak lower esophageal sphincter","Hiatal hernia","Obesity"],"risk_factors":["Obesity","Pregnancy","Smoking","Hiatal hernia","Fatty foods"],"complications":["Esophagitis","Barrett's esophagus","Esophageal stricture"],"prevention":["Maintain healthy weight","Avoid trigger foods","Don't lie down after eating","Elevate head of bed"],"home_remedies":["Avoid spicy/fatty foods","Eat smaller meals","Ginger tea","Baking soda water","Aloe vera juice"],"otc_medications":[{"category":"Antacids","examples":["Tums","Maalox"],"disclaimer":"Consult a licensed physician before use."},{"category":"H2 blockers","examples":["Famotidine","Ranitidine"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Proton pump inhibitors","Prokinetics"],"recommended_specialist":"Gastroenterologist","severity_level":"mild","avg_recovery_time":"Chronic — managed with lifestyle and medication","when_to_see_doctor":"Symptoms more than twice a week, difficulty swallowing, or unintentional weight loss.","red_flag_symptoms":["Difficulty swallowing","Vomiting blood","Black stools","Unintentional weight loss"]},

{"id":"peptic-ulcer","disease_name":"Peptic Ulcer","icd10_code":"K27","description":"Open sores that develop on the inner lining of the stomach or upper small intestine.","common_symptoms":["burning stomach pain","bloating","heartburn","nausea","intolerance to fatty foods"],"rare_symptoms":["vomiting blood","dark blood in stools","unexplained weight loss"],"causes":["H. pylori infection","Long-term NSAID use","Excess stomach acid"],"risk_factors":["H. pylori infection","Regular NSAID use","Smoking","Alcohol","Stress"],"complications":["Internal bleeding","Perforation","Gastric outlet obstruction","Gastric cancer"],"prevention":["Limit NSAIDs","Treat H. pylori","Avoid smoking","Manage stress"],"home_remedies":["Probiotics","Honey","Cabbage juice","Licorice root","Avoid spicy foods"],"otc_medications":[{"category":"Antacids","examples":["Aluminum hydroxide"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["PPIs","Antibiotics for H. pylori","H2 blockers","Sucralfate"],"recommended_specialist":"Gastroenterologist","severity_level":"moderate","avg_recovery_time":"4-8 weeks with treatment","when_to_see_doctor":"Persistent stomach pain, vomiting, or blood in stool.","red_flag_symptoms":["Vomiting blood","Black tarry stools","Sudden severe abdominal pain","Fainting"]},

{"id":"gastroenteritis","disease_name":"Gastroenteritis","icd10_code":"K52","description":"Inflammation of the stomach and intestines, commonly called stomach flu, causing diarrhea and vomiting.","common_symptoms":["diarrhea","nausea","vomiting","abdominal cramps","low-grade fever"],"rare_symptoms":["bloody diarrhea","dehydration","muscle aches"],"causes":["Norovirus","Rotavirus","Bacterial infection","Contaminated food/water"],"risk_factors":["Poor hygiene","Contaminated food","Close contact","Weakened immunity"],"complications":["Dehydration","Electrolyte imbalance","Malnutrition"],"prevention":["Hand washing","Safe food handling","Clean water","Rotavirus vaccine"],"home_remedies":["ORS (oral rehydration salts)","BRAT diet","Clear broths","Ginger tea","Rest"],"otc_medications":[{"category":"Anti-diarrheals","examples":["Loperamide"],"disclaimer":"Consult a licensed physician before use."},{"category":"ORS","examples":["Pedialyte","Electral"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antibiotics if bacterial","Antiemetics"],"recommended_specialist":"Gastroenterologist / General Physician","severity_level":"mild","avg_recovery_time":"1-3 days","when_to_see_doctor":"Unable to keep fluids down for 24 hours, blood in vomit/stool, fever above 104°F.","red_flag_symptoms":["Severe dehydration","Blood in stool","High fever","Unable to keep fluids down"]},

{"id":"ibs","disease_name":"Irritable Bowel Syndrome","icd10_code":"K58","description":"A chronic functional GI disorder affecting the large intestine, causing cramping, bloating, and altered bowel habits.","common_symptoms":["abdominal pain","bloating","gas","diarrhea","constipation","cramping"],"rare_symptoms":["mucus in stool","urgency","incomplete evacuation"],"causes":["Gut-brain axis dysfunction","Altered gut motility","Visceral hypersensitivity"],"risk_factors":["Female sex","Age under 50","Family history","Anxiety/depression","Food sensitivities"],"complications":["Poor quality of life","Mood disorders","Hemorrhoids"],"prevention":["Manage stress","Regular meals","Identify trigger foods","Exercise regularly"],"home_remedies":["Peppermint tea","Probiotics","Fiber supplements","Yoga","Low FODMAP diet"],"otc_medications":[{"category":"Fiber supplements","examples":["Psyllium","Methylcellulose"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antispasmodics","SSRIs","Rifaximin","Linaclotide"],"recommended_specialist":"Gastroenterologist","severity_level":"mild","avg_recovery_time":"Chronic — managed long-term","when_to_see_doctor":"Persistent changes in bowel habits, weight loss, or rectal bleeding.","red_flag_symptoms":["Rectal bleeding","Unexplained weight loss","Nighttime diarrhea","Anemia"]},

{"id":"hepatitis-a","disease_name":"Hepatitis A","icd10_code":"B15","description":"A highly contagious liver infection caused by the hepatitis A virus, usually from contaminated food or water.","common_symptoms":["fatigue","nausea","abdominal pain","loss of appetite","low-grade fever","dark urine","jaundice"],"rare_symptoms":["joint pain","clay-colored stools","intense itching"],"causes":["Hepatitis A virus (HAV)"],"risk_factors":["Travel to endemic areas","Poor sanitation","Close contact with infected person"],"complications":["Acute liver failure (rare)","Prolonged cholestasis"],"prevention":["Hepatitis A vaccine","Good hygiene","Safe drinking water","Proper food handling"],"home_remedies":["Rest","Adequate nutrition","Avoid alcohol","Stay hydrated"],"otc_medications":[{"category":"Supportive care","examples":["Acetaminophen for fever (low dose)"],"disclaimer":"Avoid high doses. Consult physician."}],"prescription_drug_categories":["Supportive care only — no specific antiviral"],"recommended_specialist":"Hepatologist / Gastroenterologist","severity_level":"moderate","avg_recovery_time":"2-6 months","when_to_see_doctor":"Jaundice, severe abdominal pain, or prolonged vomiting.","red_flag_symptoms":["Severe jaundice","Confusion","Severe abdominal pain","Bleeding tendency"]},

{"id":"hepatitis-b","disease_name":"Hepatitis B","icd10_code":"B16","description":"A serious liver infection caused by the hepatitis B virus, can become chronic and lead to liver failure or cancer.","common_symptoms":["fatigue","abdominal pain","nausea","jaundice","dark urine","joint pain"],"rare_symptoms":["fever","loss of appetite","clay-colored stools"],"causes":["Hepatitis B virus (HBV) — blood/body fluid contact"],"risk_factors":["Unprotected sex","Sharing needles","Mother-to-child transmission","Healthcare workers"],"complications":["Chronic hepatitis","Cirrhosis","Liver cancer","Liver failure"],"prevention":["HBV vaccination","Safe sex practices","Don't share needles","Screen blood products"],"home_remedies":["Rest","Nutritious diet","Avoid alcohol completely","Milk thistle (supportive)"],"otc_medications":[{"category":"None specific","examples":[],"disclaimer":"Requires medical management. Consult hepatologist."}],"prescription_drug_categories":["Antivirals (Entecavir, Tenofovir)","Interferon"],"recommended_specialist":"Hepatologist","severity_level":"severe","avg_recovery_time":"Acute: 1-3 months; Chronic: lifelong management","when_to_see_doctor":"Jaundice, known exposure, or if in high-risk group.","red_flag_symptoms":["Severe jaundice","Confusion","Abdominal swelling","Severe bleeding"]},

{"id":"fatty-liver","disease_name":"Fatty Liver Disease","icd10_code":"K76","description":"Accumulation of excess fat in liver cells, can be alcoholic (ALD) or non-alcoholic (NAFLD).","common_symptoms":["often asymptomatic","fatigue","discomfort in upper right abdomen"],"rare_symptoms":["abdominal swelling","jaundice","enlarged liver","spider angiomas"],"causes":["Obesity","Excessive alcohol","Insulin resistance","High triglycerides"],"risk_factors":["Obesity","Type 2 diabetes","High cholesterol","Sedentary lifestyle","Alcohol abuse"],"complications":["NASH","Fibrosis","Cirrhosis","Liver cancer"],"prevention":["Healthy weight","Regular exercise","Limit alcohol","Balanced diet"],"home_remedies":["Weight loss","Mediterranean diet","Coffee (moderate)","Exercise 30 min/day","Avoid sugar and refined carbs"],"otc_medications":[{"category":"Vitamin E","examples":["Alpha-tocopherol"],"disclaimer":"Only under medical supervision. Consult physician."}],"prescription_drug_categories":["Pioglitazone","GLP-1 agonists","Vitamin E (supervised)"],"recommended_specialist":"Hepatologist","severity_level":"mild","avg_recovery_time":"Reversible with lifestyle changes in early stages","when_to_see_doctor":"Persistent fatigue, abdominal pain, or abnormal liver enzymes.","red_flag_symptoms":["Jaundice","Abdominal swelling","Severe fatigue","Confusion"]},

{"id":"cirrhosis","disease_name":"Cirrhosis","icd10_code":"K74","description":"Late-stage liver scarring caused by many forms of liver disease, leading to liver dysfunction.","common_symptoms":["fatigue","easy bruising","jaundice","itchy skin","swelling in legs and abdomen"],"rare_symptoms":["confusion","slurred speech","spider angiomas","redness in palms"],"causes":["Chronic alcoholism","Chronic hepatitis B/C","NAFLD","Autoimmune hepatitis"],"risk_factors":["Heavy alcohol use","Chronic viral hepatitis","Obesity","Diabetes"],"complications":["Portal hypertension","Variceal bleeding","Ascites","Hepatic encephalopathy","Liver cancer"],"prevention":["Limit alcohol","Treat hepatitis","Maintain healthy weight","Avoid liver toxins"],"home_remedies":["Low-sodium diet","Avoid alcohol completely","Coffee","Adequate protein","Rest"],"otc_medications":[{"category":"None recommended","examples":[],"disclaimer":"Requires specialist management. Many OTC drugs are hepatotoxic."}],"prescription_drug_categories":["Diuretics","Lactulose","Beta-blockers","Liver transplant evaluation"],"recommended_specialist":"Hepatologist","severity_level":"severe","avg_recovery_time":"Irreversible — managed to prevent progression","when_to_see_doctor":"Jaundice, abdominal swelling, confusion, or known liver disease.","red_flag_symptoms":["Vomiting blood","Severe confusion","Rapid abdominal swelling","High fever with liver disease"]},

{"id":"ckd","disease_name":"Chronic Kidney Disease","icd10_code":"N18","description":"Gradual loss of kidney function over months or years, leading to dangerous levels of waste in the body.","common_symptoms":["fatigue","swelling in feet and ankles","decreased urination","nausea","shortness of breath"],"rare_symptoms":["muscle cramps","itching","chest pain","high blood pressure","sleep problems"],"causes":["Diabetes","Hypertension","Glomerulonephritis","Polycystic kidney disease"],"risk_factors":["Diabetes","High blood pressure","Heart disease","Family history","Age over 60"],"complications":["End-stage renal disease","Cardiovascular disease","Anemia","Bone disease","Hyperkalemia"],"prevention":["Control blood sugar","Manage blood pressure","Healthy diet","Don't overuse NSAIDs","Regular screening"],"home_remedies":["Low-sodium diet","Limit potassium","Adequate hydration","Reduce protein intake","Regular monitoring"],"otc_medications":[{"category":"Avoid NSAIDs","examples":[],"disclaimer":"Many OTC medications are harmful for kidneys. Consult nephrologist."}],"prescription_drug_categories":["ACE inhibitors","ARBs","Erythropoietin","Phosphate binders","Dialysis"],"recommended_specialist":"Nephrologist","severity_level":"severe","avg_recovery_time":"Irreversible — managed to slow progression","when_to_see_doctor":"Swelling, decreased urination, fatigue, or known risk factors.","red_flag_symptoms":["Severely reduced urination","Severe swelling","Chest pain","Seizures","Confusion"]},

{"id":"uti","disease_name":"Urinary Tract Infection","icd10_code":"N39","description":"An infection in any part of the urinary system — kidneys, ureters, bladder, or urethra.","common_symptoms":["burning urination","frequent urination","urgency","cloudy urine","pelvic pain"],"rare_symptoms":["blood in urine","strong-smelling urine","back pain","fever"],"causes":["E. coli bacteria","Sexual activity","Catheter use","Urinary tract abnormalities"],"risk_factors":["Female sex","Sexual activity","Certain birth control","Menopause","Urinary tract abnormalities"],"complications":["Kidney infection","Sepsis","Recurrent UTIs"],"prevention":["Stay hydrated","Urinate after intercourse","Wipe front to back","Avoid irritating products"],"home_remedies":["Drink plenty of water","Cranberry juice (unsweetened)","Probiotics","Vitamin C","D-Mannose"],"otc_medications":[{"category":"Urinary pain relief","examples":["Phenazopyridine"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antibiotics (Nitrofurantoin, TMP-SMX, Ciprofloxacin)"],"recommended_specialist":"Urologist","severity_level":"mild","avg_recovery_time":"3-7 days with antibiotics","when_to_see_doctor":"Symptoms persist, fever, back pain, or blood in urine.","red_flag_symptoms":["High fever","Severe back/flank pain","Vomiting","Blood in urine"]},

{"id":"kidney-stones","disease_name":"Kidney Stones","icd10_code":"N20","description":"Hard deposits of minerals and salts that form inside the kidneys and can cause severe pain when passing.","common_symptoms":["severe flank pain","pain radiating to groin","blood in urine","nausea","vomiting"],"rare_symptoms":["fever","chills","frequent urination","painful urination"],"causes":["Concentrated urine","Calcium buildup","Uric acid","Dehydration"],"risk_factors":["Dehydration","High-sodium diet","Obesity","Family history","Certain supplements"],"complications":["Urinary obstruction","Kidney infection","Kidney damage"],"prevention":["Drink 2-3 liters water daily","Low-sodium diet","Limit animal protein","Adequate calcium from food"],"home_remedies":["Drink lots of water","Lemon juice","Apple cider vinegar","Basil tea","Reduce oxalate-rich foods"],"otc_medications":[{"category":"Pain relievers","examples":["Ibuprofen","Acetaminophen"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Alpha-blockers (Tamsulosin)","Lithotripsy","Surgical removal"],"recommended_specialist":"Urologist / Nephrologist","severity_level":"moderate","avg_recovery_time":"Days to weeks depending on size","when_to_see_doctor":"Severe pain, blood in urine, fever, or unable to pass urine.","red_flag_symptoms":["Fever with stone symptoms","Complete inability to urinate","Severe persistent pain","Vomiting unable to keep fluids"]},

{"id":"dengue","disease_name":"Dengue","icd10_code":"A90","description":"A mosquito-borne viral infection causing flu-like illness, sometimes developing into severe dengue.","common_symptoms":["high fever","severe headache","pain behind eyes","joint and muscle pain","rash","nausea"],"rare_symptoms":["bleeding gums","blood in urine","severe abdominal pain","persistent vomiting"],"causes":["Dengue virus (DENV 1-4) via Aedes mosquitoes"],"risk_factors":["Living in tropical areas","Previous dengue infection","Travel to endemic areas"],"complications":["Dengue hemorrhagic fever","Dengue shock syndrome","Organ damage","Death"],"prevention":["Mosquito repellent","Eliminate standing water","Wear protective clothing","Window screens"],"home_remedies":["Complete rest","Hydration","Papaya leaf extract","Coconut water","Avoid aspirin/ibuprofen"],"otc_medications":[{"category":"Antipyretics","examples":["Acetaminophen ONLY (avoid NSAIDs)"],"disclaimer":"Do NOT take aspirin or ibuprofen. Consult physician."}],"prescription_drug_categories":["IV fluids","Platelet transfusion if needed","Supportive care"],"recommended_specialist":"Infectious Disease / General Physician","severity_level":"moderate","avg_recovery_time":"2-7 days for mild; weeks for severe","when_to_see_doctor":"High fever with rash, bleeding, severe abdominal pain, or persistent vomiting.","red_flag_symptoms":["Severe abdominal pain","Persistent vomiting","Bleeding","Rapid breathing","Fatigue/restlessness"]},

{"id":"malaria","disease_name":"Malaria","icd10_code":"B54","description":"A life-threatening disease caused by Plasmodium parasites transmitted through infected Anopheles mosquito bites.","common_symptoms":["high fever with chills","sweating","headache","nausea","vomiting","body aches","fatigue"],"rare_symptoms":["jaundice","seizures","confusion","bloody stools","anemia"],"causes":["Plasmodium falciparum","P. vivax","P. ovale","P. malariae"],"risk_factors":["Travel to endemic areas","Lack of immunity","No mosquito protection","Young children","Pregnant women"],"complications":["Cerebral malaria","Severe anemia","Organ failure","Death"],"prevention":["Antimalarial prophylaxis","Mosquito nets","Repellent","Indoor spraying"],"home_remedies":["Complete rest","Hydration","Citrus fruits","Cinnamon tea","Ginger"],"otc_medications":[{"category":"Antipyretics","examples":["Acetaminophen"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Chloroquine","Artemisinin-based combination therapy","Primaquine"],"recommended_specialist":"Infectious Disease","severity_level":"severe","avg_recovery_time":"2 weeks with treatment","when_to_see_doctor":"Fever after visiting endemic area, cyclic fevers, or any suspected case.","red_flag_symptoms":["Confusion","Seizures","Severe anemia","Jaundice","Difficulty breathing"]},

{"id":"typhoid","disease_name":"Typhoid Fever","icd10_code":"A01","description":"A bacterial infection caused by Salmonella typhi, spread through contaminated food and water.","common_symptoms":["sustained high fever","headache","abdominal pain","constipation or diarrhea","weakness","rose spots on trunk"],"rare_symptoms":["confusion","intestinal bleeding","hepatomegaly","splenomegaly"],"causes":["Salmonella typhi bacteria"],"risk_factors":["Travel to endemic areas","Poor sanitation","Contaminated food/water","Close contact"],"complications":["Intestinal perforation","Internal bleeding","Myocarditis","Meningitis"],"prevention":["Typhoid vaccine","Safe drinking water","Proper food handling","Hand hygiene"],"home_remedies":["Complete rest","Hydration","Soft easily digestible food","ORS","Cold compresses for fever"],"otc_medications":[{"category":"ORS","examples":["Electral","Pedialyte"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antibiotics (Azithromycin, Ceftriaxone, Ciprofloxacin)"],"recommended_specialist":"Infectious Disease / General Physician","severity_level":"moderate","avg_recovery_time":"3-5 days on antibiotics; 2-4 weeks total","when_to_see_doctor":"Sustained fever, abdominal pain, or travel to endemic areas.","red_flag_symptoms":["Severe abdominal pain","Bloody stool","Confusion","Very high fever"]},

{"id":"chickenpox","disease_name":"Chickenpox","icd10_code":"B01","description":"A highly contagious viral infection caused by varicella-zoster virus, causing itchy blister-like rash.","common_symptoms":["itchy blistering rash","fever","fatigue","headache","loss of appetite"],"rare_symptoms":["rash spreading to eyes","difficulty breathing","stiff neck"],"causes":["Varicella-zoster virus (VZV)"],"risk_factors":["No prior infection or vaccination","Young children","Immunocompromised","Pregnancy"],"complications":["Bacterial skin infections","Pneumonia","Encephalitis","Reye's syndrome"],"prevention":["Varicella vaccine","Avoid contact with infected","Good hygiene"],"home_remedies":["Calamine lotion","Oatmeal baths","Cool compresses","Trim fingernails","Baking soda baths"],"otc_medications":[{"category":"Antihistamines","examples":["Diphenhydramine"],"disclaimer":"Consult a licensed physician before use. Avoid aspirin in children."}],"prescription_drug_categories":["Acyclovir","Valacyclovir"],"recommended_specialist":"General Physician / Dermatologist","severity_level":"mild","avg_recovery_time":"5-10 days","when_to_see_doctor":"Rash near eyes, high fever, confusion, or breathing difficulty.","red_flag_symptoms":["Rash near eyes","High fever","Stiff neck","Difficulty breathing","Severe skin infection"]}
]

def get_part2():
    return DISEASES_PART2

if __name__ == "__main__":
    from pathlib import Path
    dest = Path(__file__).resolve().parent.parent.parent / "knowledge_base"
    dest.mkdir(parents=True, exist_ok=True)
    with open(dest / "diseases_part2.json", "w") as f:
        json.dump(DISEASES_PART2, f, indent=2)
    print(f"[OK] Part 2: {len(DISEASES_PART2)} diseases")
