"""KB Generator Part 1 — first 15 diseases."""
import json
from pathlib import Path

DISEASES_PART1 = [
{"id":"common-cold","disease_name":"Common Cold","icd10_code":"J00","description":"A viral infection of the upper respiratory tract affecting the nose and throat. Usually harmless and self-limiting.","common_symptoms":["runny nose","sneezing","sore throat","cough","congestion","mild headache","mild body aches"],"rare_symptoms":["mild fever","watery eyes","reduced smell"],"causes":["Rhinoviruses","Coronaviruses","RSV","Adenoviruses"],"risk_factors":["Young age","Weakened immunity","Seasonal changes","Close contact with infected"],"complications":["Ear infection","Sinusitis","Asthma attacks","Secondary infections"],"prevention":["Wash hands frequently","Avoid close contact with sick individuals","Disinfect surfaces","Maintain good sleep"],"home_remedies":["Rest and hydration","Warm salt water gargle","Honey and lemon tea","Steam inhalation","Chicken soup"],"otc_medications":[{"category":"Decongestants","examples":["Pseudoephedrine","Phenylephrine"],"disclaimer":"Consult a licensed physician before use."},{"category":"Antihistamines","examples":["Cetirizine","Loratadine"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Rarely needed"],"recommended_specialist":"General Physician","severity_level":"mild","avg_recovery_time":"7-10 days","when_to_see_doctor":"If symptoms last more than 10 days, fever above 101.3°F, or symptoms worsen.","red_flag_symptoms":["High fever","Severe headache","Difficulty breathing","Persistent chest pain"]},

{"id":"influenza","disease_name":"Influenza","icd10_code":"J11","description":"A contagious respiratory illness caused by influenza viruses that infect the nose, throat, and lungs.","common_symptoms":["high fever","body aches","fatigue","cough","headache","chills","sore throat"],"rare_symptoms":["vomiting","diarrhea","eye pain"],"causes":["Influenza A virus","Influenza B virus"],"risk_factors":["Age over 65","Chronic conditions","Pregnancy","Weakened immune system"],"complications":["Pneumonia","Bronchitis","Sinus infections","Myocarditis"],"prevention":["Annual flu vaccine","Hand hygiene","Avoid crowds during flu season"],"home_remedies":["Complete bed rest","Plenty of fluids","Warm soups","Humidifier use"],"otc_medications":[{"category":"Antipyretics","examples":["Acetaminophen","Ibuprofen"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antivirals (Oseltamivir, Zanamivir)"],"recommended_specialist":"General Physician / Pulmonologist","severity_level":"moderate","avg_recovery_time":"1-2 weeks","when_to_see_doctor":"If fever persists beyond 3 days, difficulty breathing, or chest pain.","red_flag_symptoms":["Difficulty breathing","Persistent chest pain","Confusion","Severe vomiting"]},

{"id":"covid-19","disease_name":"COVID-19","icd10_code":"U07.1","description":"An infectious disease caused by the SARS-CoV-2 virus affecting the respiratory system and potentially other organs.","common_symptoms":["fever","dry cough","fatigue","loss of taste","loss of smell","body aches","sore throat"],"rare_symptoms":["skin rash","discoloration of fingers","conjunctivitis"],"causes":["SARS-CoV-2 virus"],"risk_factors":["Age over 60","Obesity","Diabetes","Heart disease","Immunocompromised"],"complications":["Pneumonia","ARDS","Organ failure","Long COVID"],"prevention":["Vaccination","Mask wearing","Hand hygiene","Social distancing"],"home_remedies":["Rest","Hydration","Steam inhalation","Prone positioning"],"otc_medications":[{"category":"Antipyretics","examples":["Acetaminophen"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antivirals (Paxlovid)","Monoclonal antibodies","Corticosteroids"],"recommended_specialist":"Pulmonologist / Infectious Disease","severity_level":"moderate","avg_recovery_time":"2-6 weeks","when_to_see_doctor":"Difficulty breathing, persistent chest pain, oxygen levels below 94%.","red_flag_symptoms":["Severe breathlessness","Oxygen below 94%","Persistent chest pressure","Confusion","Bluish lips"]},

{"id":"pneumonia","disease_name":"Pneumonia","icd10_code":"J18","description":"An infection that inflames the air sacs in one or both lungs, which may fill with fluid or pus.","common_symptoms":["cough with phlegm","fever","chills","shortness of breath","chest pain when breathing"],"rare_symptoms":["confusion in elderly","nausea","lower than normal temperature"],"causes":["Bacteria (Streptococcus)","Viruses","Fungi","Aspiration"],"risk_factors":["Age over 65 or under 2","Chronic lung disease","Smoking","Weakened immune system"],"complications":["Bacteremia","Pleural effusion","Lung abscess","Respiratory failure"],"prevention":["Pneumococcal vaccine","Good hygiene","No smoking","Strong immunity"],"home_remedies":["Rest","Warm fluids","Humidifier","Breathing exercises"],"otc_medications":[{"category":"Cough suppressants","examples":["Dextromethorphan"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Antibiotics","Antivirals","Antifungals"],"recommended_specialist":"Pulmonologist","severity_level":"severe","avg_recovery_time":"1-3 weeks","when_to_see_doctor":"Immediately if breathing difficulty, high fever, or coughing blood.","red_flag_symptoms":["Severe breathing difficulty","Coughing blood","High fever above 102°F","Confusion"]},

{"id":"asthma","disease_name":"Asthma","icd10_code":"J45","description":"A chronic condition in which airways narrow and swell, producing extra mucus, making breathing difficult.","common_symptoms":["wheezing","shortness of breath","chest tightness","coughing especially at night"],"rare_symptoms":["rapid breathing","difficulty speaking","anxiety"],"causes":["Genetic predisposition","Environmental allergens","Respiratory infections"],"risk_factors":["Family history","Allergies","Obesity","Smoking exposure","Air pollution"],"complications":["Status asthmaticus","Permanent airway remodeling","Reduced quality of life"],"prevention":["Avoid triggers","Use preventive inhalers","Regular check-ups","Clean environment"],"home_remedies":["Breathing exercises","Steam inhalation","Ginger tea","Stay upright during attacks"],"otc_medications":[{"category":"Bronchodilators","examples":["Salbutamol inhaler"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Inhaled corticosteroids","Long-acting beta-agonists","Leukotriene modifiers"],"recommended_specialist":"Pulmonologist / Allergist","severity_level":"moderate","avg_recovery_time":"Chronic condition — managed, not cured","when_to_see_doctor":"Worsening symptoms, frequent attacks, or rescue inhaler used more than twice a week.","red_flag_symptoms":["Severe breathlessness","Cannot speak in sentences","Blue lips","No relief from inhaler"]},

{"id":"bronchitis","disease_name":"Bronchitis","icd10_code":"J20","description":"Inflammation of the bronchial tubes that carry air to and from the lungs.","common_symptoms":["persistent cough","mucus production","fatigue","shortness of breath","chest discomfort"],"rare_symptoms":["wheezing","mild fever","body aches"],"causes":["Viral infections","Bacterial infections","Irritant exposure","Smoking"],"risk_factors":["Smoking","Weak immunity","GERD","Occupational exposure"],"complications":["Pneumonia","Chronic bronchitis","COPD"],"prevention":["Avoid smoking","Wash hands","Wear masks in polluted areas"],"home_remedies":["Rest","Warm fluids","Honey","Humidifier","Steam inhalation"],"otc_medications":[{"category":"Expectorants","examples":["Guaifenesin"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Bronchodilators","Antibiotics if bacterial"],"recommended_specialist":"Pulmonologist","severity_level":"mild","avg_recovery_time":"1-3 weeks","when_to_see_doctor":"Cough lasting more than 3 weeks, blood in mucus, or high fever.","red_flag_symptoms":["Coughing blood","Fever above 100.4°F for 3+ days","Severe breathing difficulty"]},

{"id":"tuberculosis","disease_name":"Tuberculosis","icd10_code":"A15","description":"A serious infectious disease caused by Mycobacterium tuberculosis, mainly affecting the lungs.","common_symptoms":["persistent cough over 3 weeks","coughing blood","night sweats","weight loss","fever","fatigue"],"rare_symptoms":["chest pain","loss of appetite","swollen lymph nodes"],"causes":["Mycobacterium tuberculosis"],"risk_factors":["HIV infection","Close contact with TB patients","Malnutrition","Crowded living conditions"],"complications":["Miliary TB","TB meningitis","Organ damage","Drug-resistant TB"],"prevention":["BCG vaccine","Early detection","Proper ventilation","Complete treatment"],"home_remedies":["Nutritious diet","Rest","Sunlight exposure","Garlic and turmeric"],"otc_medications":[{"category":"Supportive","examples":["Multivitamins"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Isoniazid","Rifampicin","Pyrazinamide","Ethambutol"],"recommended_specialist":"Pulmonologist / Infectious Disease","severity_level":"severe","avg_recovery_time":"6-9 months with treatment","when_to_see_doctor":"Immediately if persistent cough, coughing blood, or unexplained weight loss.","red_flag_symptoms":["Coughing blood","Severe weight loss","Persistent high fever","Difficulty breathing"]},

{"id":"migraine","disease_name":"Migraine","icd10_code":"G43","description":"A neurological condition characterized by intense, debilitating headaches often accompanied by nausea and sensitivity to light.","common_symptoms":["throbbing headache","nausea","sensitivity to light","sensitivity to sound","visual aura"],"rare_symptoms":["numbness","tingling","difficulty speaking","vertigo"],"causes":["Genetic factors","Hormonal changes","Triggers (stress, food, sleep)"],"risk_factors":["Family history","Female sex","Hormonal changes","Stress","Sleep irregularity"],"complications":["Chronic migraine","Status migrainosus","Stroke risk"],"prevention":["Regular sleep","Stress management","Avoid triggers","Stay hydrated"],"home_remedies":["Dark quiet room","Cold compress","Peppermint oil","Ginger tea","Adequate sleep"],"otc_medications":[{"category":"Pain relievers","examples":["Ibuprofen","Acetaminophen","Aspirin"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Triptans","CGRP inhibitors","Beta-blockers","Anticonvulsants"],"recommended_specialist":"Neurologist","severity_level":"moderate","avg_recovery_time":"4-72 hours per episode","when_to_see_doctor":"New or worsening headaches, aura lasting over an hour, or more than 15 headache days per month.","red_flag_symptoms":["Sudden severe headache","Headache with fever and stiff neck","Vision loss","Confusion"]},

{"id":"hypertension","disease_name":"Hypertension","icd10_code":"I10","description":"A chronic condition where blood pressure in the arteries is persistently elevated, increasing risk of heart disease and stroke.","common_symptoms":["often asymptomatic","headache","dizziness","shortness of breath"],"rare_symptoms":["nosebleeds","visual changes","chest pain","blood in urine"],"causes":["Essential (primary) — unknown","Secondary — kidney disease, hormonal disorders"],"risk_factors":["Obesity","High salt diet","Sedentary lifestyle","Family history","Age","Stress"],"complications":["Heart attack","Stroke","Heart failure","Kidney damage","Vision loss"],"prevention":["Low sodium diet","Regular exercise","Healthy weight","Limit alcohol","Stress management"],"home_remedies":["DASH diet","Regular walking","Reduce salt","Potassium-rich foods","Meditation"],"otc_medications":[{"category":"None recommended","examples":[],"disclaimer":"Blood pressure medication requires prescription. Consult a physician."}],"prescription_drug_categories":["ACE inhibitors","ARBs","Calcium channel blockers","Diuretics","Beta-blockers"],"recommended_specialist":"Cardiologist","severity_level":"moderate","avg_recovery_time":"Lifelong management","when_to_see_doctor":"BP consistently above 140/90, headaches, vision changes, or chest pain.","red_flag_symptoms":["BP above 180/120","Severe headache","Chest pain","Vision changes","Confusion"]},

{"id":"type-2-diabetes","disease_name":"Type 2 Diabetes","icd10_code":"E11","description":"A chronic metabolic condition where the body becomes resistant to insulin or doesn't produce enough insulin.","common_symptoms":["increased thirst","frequent urination","fatigue","blurred vision","slow wound healing"],"rare_symptoms":["tingling in hands/feet","dark skin patches","recurrent infections"],"causes":["Insulin resistance","Genetic factors","Lifestyle factors"],"risk_factors":["Obesity","Sedentary lifestyle","Family history","Age over 45","PCOS"],"complications":["Cardiovascular disease","Neuropathy","Nephropathy","Retinopathy","Foot ulcers"],"prevention":["Healthy diet","Regular exercise","Maintain healthy weight","Regular screening"],"home_remedies":["Low-glycemic diet","Regular walking","Fenugreek seeds","Cinnamon","Bitter gourd juice"],"otc_medications":[{"category":"Blood glucose monitors","examples":["Glucometer strips"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Metformin","Sulfonylureas","DPP-4 inhibitors","SGLT2 inhibitors","Insulin"],"recommended_specialist":"Endocrinologist","severity_level":"moderate","avg_recovery_time":"Lifelong management","when_to_see_doctor":"Fasting glucose above 126 mg/dL, symptoms of hyperglycemia, or foot sores.","red_flag_symptoms":["Very high blood sugar","Diabetic ketoacidosis symptoms","Sudden vision changes","Non-healing wounds"]},

{"id":"coronary-artery-disease","disease_name":"Coronary Artery Disease","icd10_code":"I25","description":"A condition where coronary arteries become narrowed or blocked due to plaque buildup, reducing blood flow to the heart.","common_symptoms":["chest pain (angina)","shortness of breath","fatigue during exertion"],"rare_symptoms":["jaw pain","arm pain","nausea","sweating"],"causes":["Atherosclerosis","Plaque buildup in coronary arteries"],"risk_factors":["High cholesterol","High blood pressure","Smoking","Diabetes","Obesity","Family history"],"complications":["Heart attack","Heart failure","Arrhythmias","Sudden cardiac death"],"prevention":["Heart-healthy diet","Regular exercise","No smoking","Manage cholesterol and BP"],"home_remedies":["Heart-healthy diet","Regular walking","Omega-3 fatty acids","Stress reduction","Garlic"],"otc_medications":[{"category":"Aspirin (low-dose)","examples":["Aspirin 81mg"],"disclaimer":"Only under physician guidance. Consult before use."}],"prescription_drug_categories":["Statins","ACE inhibitors","Beta-blockers","Antiplatelet agents","Nitrates"],"recommended_specialist":"Cardiologist","severity_level":"severe","avg_recovery_time":"Lifelong management","when_to_see_doctor":"Chest pain, shortness of breath on exertion, or known risk factors.","red_flag_symptoms":["Crushing chest pain","Pain radiating to arm/jaw","Sudden breathlessness","Cold sweat","Fainting"]},

{"id":"heart-failure","disease_name":"Heart Failure","icd10_code":"I50","description":"A chronic condition where the heart doesn't pump blood as well as it should to meet the body's needs.","common_symptoms":["shortness of breath","fatigue","swollen legs","rapid heartbeat","persistent cough"],"rare_symptoms":["abdominal swelling","sudden weight gain","reduced alertness"],"causes":["Coronary artery disease","High blood pressure","Cardiomyopathy","Valve disease"],"risk_factors":["Previous heart attack","Coronary artery disease","Hypertension","Diabetes","Obesity"],"complications":["Kidney damage","Liver damage","Pulmonary edema","Cardiac arrest"],"prevention":["Manage BP and cholesterol","Healthy lifestyle","Limit alcohol","Regular check-ups"],"home_remedies":["Low-sodium diet","Fluid restriction","Daily weight monitoring","Leg elevation","Light walking"],"otc_medications":[{"category":"None recommended","examples":[],"disclaimer":"Heart failure requires prescription management. Consult cardiologist."}],"prescription_drug_categories":["ACE inhibitors","ARBs","Beta-blockers","Diuretics","Aldosterone antagonists"],"recommended_specialist":"Cardiologist","severity_level":"severe","avg_recovery_time":"Lifelong management","when_to_see_doctor":"Worsening breathlessness, sudden weight gain, or swelling.","red_flag_symptoms":["Severe breathlessness at rest","Coughing pink frothy mucus","Fainting","Rapid irregular heartbeat"]},

{"id":"anemia","disease_name":"Anemia","icd10_code":"D64","description":"A condition where blood lacks enough healthy red blood cells or hemoglobin to carry adequate oxygen to tissues.","common_symptoms":["fatigue","weakness","pale skin","shortness of breath","dizziness","cold hands and feet"],"rare_symptoms":["brittle nails","unusual cravings (pica)","tongue soreness","headache"],"causes":["Iron deficiency","Vitamin B12 deficiency","Chronic disease","Bone marrow disorders"],"risk_factors":["Poor diet","Menstruation","Pregnancy","Chronic conditions","Family history"],"complications":["Severe fatigue","Heart problems","Pregnancy complications","Death in severe cases"],"prevention":["Iron-rich diet","Vitamin C for absorption","Regular blood tests","Prenatal vitamins"],"home_remedies":["Iron-rich foods (spinach, lentils, red meat)","Vitamin C foods","Beetroot juice","Blackstrap molasses","Dates and raisins"],"otc_medications":[{"category":"Iron supplements","examples":["Ferrous sulfate","Ferrous gluconate"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Iron injections","B12 injections","Erythropoietin","Blood transfusion"],"recommended_specialist":"Hematologist","severity_level":"moderate","avg_recovery_time":"2-3 months with treatment","when_to_see_doctor":"Persistent fatigue, pale skin, or shortness of breath.","red_flag_symptoms":["Severe weakness","Rapid heartbeat","Chest pain","Fainting"]},

{"id":"hypothyroidism","disease_name":"Hypothyroidism","icd10_code":"E03","description":"A condition where the thyroid gland doesn't produce enough thyroid hormone, slowing metabolism.","common_symptoms":["fatigue","weight gain","cold intolerance","dry skin","constipation","depression"],"rare_symptoms":["muscle weakness","hoarse voice","puffy face","elevated cholesterol","joint pain"],"causes":["Hashimoto's thyroiditis","Thyroid surgery","Radiation therapy","Iodine deficiency"],"risk_factors":["Female sex","Age over 60","Family history","Autoimmune disease"],"complications":["Goiter","Heart disease","Myxedema","Infertility","Birth defects"],"prevention":["Adequate iodine intake","Regular thyroid screening","Early treatment"],"home_remedies":["Iodine-rich foods","Selenium-rich foods","Regular exercise","Coconut oil","Avoid goitrogens"],"otc_medications":[{"category":"Iodine supplements","examples":["Iodized salt"],"disclaimer":"Consult a licensed physician before use."}],"prescription_drug_categories":["Levothyroxine"],"recommended_specialist":"Endocrinologist","severity_level":"moderate","avg_recovery_time":"Lifelong medication management","when_to_see_doctor":"Persistent fatigue, unexplained weight gain, or cold intolerance.","red_flag_symptoms":["Severe fatigue","Extreme cold intolerance","Swelling in neck","Mental fog","Very slow heart rate"]},

{"id":"hyperthyroidism","disease_name":"Hyperthyroidism","icd10_code":"E05","description":"A condition where the thyroid gland produces too much thyroid hormone, accelerating metabolism.","common_symptoms":["weight loss","rapid heartbeat","anxiety","tremor","heat intolerance","sweating","irritability"],"rare_symptoms":["bulging eyes","skin thinning","muscle weakness","menstrual changes"],"causes":["Graves' disease","Thyroid nodules","Thyroiditis","Excess iodine"],"risk_factors":["Female sex","Family history","Personal history of autoimmune disease"],"complications":["Heart problems","Brittle bones","Thyroid storm","Eye problems"],"prevention":["Regular thyroid screening","Avoid excess iodine","Manage stress"],"home_remedies":["Lemon balm tea","Bugleweed","Stress reduction","Cool environment","Calcium-rich diet"],"otc_medications":[{"category":"Beta-blockers (for symptoms)","examples":[],"disclaimer":"Requires prescription. Consult endocrinologist."}],"prescription_drug_categories":["Anti-thyroid drugs (Methimazole)","Radioactive iodine","Beta-blockers"],"recommended_specialist":"Endocrinologist","severity_level":"moderate","avg_recovery_time":"Weeks to months with treatment","when_to_see_doctor":"Rapid heartbeat, unexplained weight loss, or tremor.","red_flag_symptoms":["Very rapid heartbeat","High fever with thyroid symptoms","Confusion","Extreme agitation"]}
]

def get_part1():
    return DISEASES_PART1

if __name__ == "__main__":
    dest = Path(__file__).resolve().parent.parent.parent / "knowledge_base"
    dest.mkdir(parents=True, exist_ok=True)
    with open(dest / "diseases_part1.json", "w") as f:
        json.dump(DISEASES_PART1, f, indent=2)
    print(f"[OK] Part 1: {len(DISEASES_PART1)} diseases")
