"""
Predictive Healthcare System — Core Configuration

Central configuration management using pydantic-settings.
All settings are loaded from environment variables or .env file.
"""

from pathlib import Path
from functools import lru_cache
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # Application
    APP_NAME: str = "Predictive Healthcare System"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    # Database
    DATABASE_URL: str = "sqlite:///./phs.db"


    # CORS
    FRONTEND_URL: str = "http://localhost:5173"

    # Server
    BACKEND_HOST: str = "0.0.0.0"
    BACKEND_PORT: int = 8000


    # ML
    ML_ARTIFACTS_DIR: str = str(Path(__file__).resolve().parent.parent.parent.parent / "ml" / "artifacts")
    MODEL_REGISTRY_PATH: str = str(Path(__file__).resolve().parent.parent.parent.parent / "ml" / "artifacts" / "registry.json")

    # File upload
    MAX_UPLOAD_SIZE: int = 5 * 1024 * 1024  # 5 MB
    ALLOWED_IMAGE_TYPES: list[str] = ["image/jpeg", "image/png", "image/bmp", "image/webp"]

    # Medical disclaimer
    MEDICAL_DISCLAIMER: str = (
        "⚠️ MEDICAL DISCLAIMER: This is an academic project developed for educational purposes only. "
        "It is NOT a certified medical device and should NOT be used for actual medical diagnosis, "
        "treatment, or clinical decision-making. Always consult a licensed healthcare professional "
        "for medical advice. The predictions and recommendations provided are generated by machine "
        "learning models trained on limited datasets and may be inaccurate or incomplete."
    )

    model_config = {
        "env_file": ".env",
        "env_file_encoding": "utf-8",
        "extra": "ignore",
    }


@lru_cache()
def get_settings() -> Settings:
    """Return cached settings instance."""
    return Settings()
